parameters:
#    eps_user.example.class: Eps\UserBundle\Example

services:
#    eps_user.example:
#        class: %eps_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
