parameters:
#    eps_photo.example.class: Eps\PhotoBundle\Example

services:
#    eps_photo.example:
#        class: %eps_photo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
