parameters:
#    eps_static_pages.example.class: Eps\StaticPagesBundle\Example

services:
#    eps_static_pages.example:
#        class: %eps_static_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
