parameters:
#    eps_homepage.example.class: Eps\HomepageBundle\Example

services:
#    eps_homepage.example:
#        class: %eps_homepage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
