reporter:
    pattern:  /reporter
    defaults: { _controller: EpsReporterBundle:Default:index }

reporter_album_new:
    pattern:  /reporter/album/new
    defaults: { _controller: EpsReporterBundle:AlbumCreate:index }

reporter_album_addphotos:
    pattern:  /reporter/album/addphotos/{id}
    defaults: { _controller: EpsReporterBundle:AlbumCreate:addPhotos }

reporter_album_upload:
    pattern:  /reporter/album/addphotos/upload
    defaults: { _controller: EpsReporterBundle:AlbumCreate:upload }

reporter_albums:
    pattern:  /albums/reporter/{id}
    defaults: { _controller: EpsReporterBundle:Default:albumsView }

reporter_albums_paginated:
    pattern:  /albums/reporter/{id}/page/{page}
    defaults: { _controller: EpsReporterBundle:Default:albumsView }